# Site settings
title: '"Ming Ki" Chong'
description: My Online Space
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: '"Ming Ki" Chong'
user_description: hello world
user_title: hello world
email_address: unexpected.exception@gmail.com
#twitter_username: lorem_ipsum
github_username:  mingkichong
#gplus_username:  lorem_ipsum
linkedin_username: mingkichong

# Google-analytics
google-analytics:
  id: ""

google-scholar:
  user: 'SGrCJqMAAAAJ'

exclude: ['package.json', 'src' , 'node_modules']
