# Site settings
title:              'Ming_Ki Chong'
description:        'this is my unexpected online exception'

# User settings
username:           'Ming_Ki Chong'
user_description:   'I am an unexpected exception that just happened to happen'
email_address :     '<strong>unexpected&bull;exception<i class="fas fa-at"></i>gmail&bull;com</strong>'
github_username:    'mingkichong'
linkedin_username:  'mingkichong'
youtube_username:   'unexpectedexception'

google_play_app:     'MKC+apps' #changing to unexpected.exception

include_about:       true
include_project:     true
include_publication: true
include_skills:      true
include_summary:     true

# Google-analytics
google-analytics:
  id: "UA-119687639-1"

google-scholar:
  user: 'SGrCJqMAAAAJ'

publications:
  my_author_name:           'Ming Ki Chong'
  highlight_my_author_name: true

exclude: ['package.json', 'src' , 'node_modules']
