# Site settings
title:              'Ming_Ki Chong'
description:        'this is my unexpected online exception'
url:                'https://www.mingkichong.net'
baseurl:            ''
lang:               'en'
author:             'Ming Ki Chong'
timezone:           'America/Los_Angeles'

# User settings
username:           'Ming_Ki Chong'
user_description:   'I am an unexpected exception that just happened to happen'
email_address:      '<strong>hello<i class="fas fa-at"></i>mingkichong&bull;net</strong>'
github_username:    'mingkichong'
linkedin_username:  'mingkichong'

include_publication: true
include_summary:     true

publications:
  my_author_name:           'Ming Ki Chong'
  highlight_my_author_name: true

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - run.sh
